on: push

defaults:
  run:
    working-directory: 'vscode'

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "centos"
            tag: "7"
          - image: "rockylinux"
            tag: "8"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'vscode'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install tox
        run: pip3 install tox

      - name: Run tox
        run: tox
        env:
          ANSIBLE_FORCE_COLOR: '1'
          IMAGE: ${{ matrix.config.image }}
          TAG: ${{ matrix.config.tag }}
